### ISSUE TITLE
Error when running project_controller.py

### ISSUE THREAD

**Issue by SandySingh** [RBerkheimer/harness#1]
When I tried to run "python project_controller.py " as in the 6th step of the DEVELOPMENT_README, I got a not found error - 

> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Progra~1\\Python36\\lib\\site-packages\\harness-0.0.1-py3.6.egg\\harness\\src\\main\\dao\\filesystemstandard'

I've checked the directory and there is no file or directory named **filesystemstandard** there but a directory named **filesystem** is there.

**Comment by RBerkheimer** [comment]
Ok, thanks for working to get the project setup and opening this - I'll get the build process standardized with pipenv and have an automated build running on CircleCI by tomorrow so we can validate.

**Comment by RBerkheimer** [comment]
Also we're going to link this to issues #3 and #2 and update the README/DEVELOPMENT README to support this

**Comment by RBerkheimer** [comment]
Sandy, is this resolved? Please let me know.

**Comment by SandySingh** [comment]
Now there isn't any **FileNotFoundError** when running "python project_controller.py"

**Comment by RBerkheimer** [comment]
Issue demonstrated as fixed on several different user configs and systems, confirmed by at least one other user and automated build.
