### ISSUE TITLE
Update Installation section of Readme to help with new users/developers

### ISSUE THREAD

**Issue by RBerkheimer** [RBerkheimer/harness#10]
Now that @ShriyaSalian has successfully built the project (!) and gotten all of the pieces put together, the project README should be updated (the installation/development section) with screenshots, information, and relevant tips from the perspective of a new user installing the system from scratch. This will help others bootstrap the project to help with contributions.

**Comment by RBerkheimer** [comment]
@SandySingh Sandy, this should help with your issue - I worked through with @ShriyaSalian today.

**Comment by ShriyaSalian** [comment]
This has been taken care of in #13 @RBerkheimer
